compatibility_date = "2024-03-09"
name = "kevinkipp-og-images"
main = "src/index.ts"
account_id = "05ad7d0f596e69b4738691b86e5f1e95"
node_compat = true
workers_dev = true

browser = { binding = "BROWSER" }

[[r2_buckets]]
binding = 'IMAGES_BUCKET'
bucket_name = 'kevinkipp-og-images'
preview_bucket_name = 'kevinkipp-og-images-dev'
